# CMake generated Testfile for 
# Source directory: /mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2
# Build directory: /mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(GTK2Components.gtk "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gtk" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Components/gtk" "--build-generator" "Unix Makefiles" "--build-target" "gtk-all-libs" "--build-project" "gtk" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Components/gtk" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.glib "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/glib" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/glib" "--build-generator" "Unix Makefiles" "--build-project" "glib" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/glib" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gobject "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gobject" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gobject" "--build-generator" "Unix Makefiles" "--build-project" "gobject" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gobject" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gio "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gio" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gio" "--build-generator" "Unix Makefiles" "--build-project" "gio" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gio" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gmodule "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gmodule" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gmodule" "--build-generator" "Unix Makefiles" "--build-project" "gmodule" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gmodule" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gthread "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gthread" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gthread" "--build-generator" "Unix Makefiles" "--build-project" "gthread" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gthread" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.atk "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/atk" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/atk" "--build-generator" "Unix Makefiles" "--build-project" "atk" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/atk" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gdk_pixbuf "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gdk_pixbuf" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--build-generator" "Unix Makefiles" "--build-project" "gdk_pixbuf" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gdk_pixbuf" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.cairo "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/cairo" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/cairo" "--build-generator" "Unix Makefiles" "--build-project" "cairo" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/cairo" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.pango "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/pango" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pango" "--build-generator" "Unix Makefiles" "--build-project" "pango" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pango" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.pangocairo "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/pangocairo" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pangocairo" "--build-generator" "Unix Makefiles" "--build-project" "pangocairo" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pangocairo" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.pangoxft "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/pangoxft" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pangoxft" "--build-generator" "Unix Makefiles" "--build-project" "pangoxft" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pangoxft" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.pangoft2 "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/pangoft2" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pangoft2" "--build-generator" "Unix Makefiles" "--build-project" "pangoft2" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/pangoft2" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gdk "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gdk" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gdk" "--build-generator" "Unix Makefiles" "--build-project" "gdk" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gdk" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
add_test(GTK2Targets.gtk "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "--build-and-test" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/gtk" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gtk" "--build-generator" "Unix Makefiles" "--build-project" "gtk" "--build-exe-dir" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/Tests/FindGTK2/GTK2Targets/gtk" "--force-new-ctest-process" "--test-command" "/mnt/NewData/work/hyperdata/trunk/modules/ml-engine/tools/cmake-3.11.3/bin/ctest" "-V")
