
/******************************************************************************
 * !!!! Do not modify this file directly !!!!
 * This file is generated by 'scripts/gen_request_enum_java.pl'.
 ******************************************************************************/

package com.tmax.hyperdata.processor;

import com.tmax.hyperdata.processor.impl.*;

public enum ETbHyperDataRequest {
    EXECUTE_FLOW_DIRECT("executeFlowDirect", new ExecuteFlowDirectProcessor()),
    REQUEST_MAX(null, null);

    /* request name */
    private String value;

    /* return request name */
    public String getValue() {
        return value;
    }

    /* processor instance */
    private ITbHyperDataRequestProcessor processorInstance;

    /* return processor instance */
    public ITbHyperDataRequestProcessor getProcessor() {
        return processorInstance;
    }

    /* Constructor */
    private ETbHyperDataRequest(String v, ITbHyperDataRequestProcessor i) {
        value = v;
        processorInstance = i;
    }

    @Override
    public String toString() {
        return value + ":" + processorInstance.getClass().getName();
    }

    /**
     * Get enumeration by value.
     * @param v request name
     * @return request enumeration
     */
    public static ETbHyperDataRequest getEnum(String v) {
        for (ETbHyperDataRequest request : ETbHyperDataRequest.values()) {
            if (request.getValue().equals(v))
                return request;
        }
        return null;
    }
}
