<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns4:message
    xmlns:ns2="http://www.tmax.co.kr/proobject/resource"
    xmlns:ns3="http://www.tmax.co.kr/proobject/dataobject"
    xmlns:ns4="http://www.tmax.co.kr/proobject/message"
    xmlns:ns5="http://www.tmax.co.kr/proobject/dto"
    xmlns:ns6="http://www.tmax.co.kr/proobject/dbio-config"
    xmlns:ns7="http://www.example.org/externalObjectConfig"
    xmlns:ns8="http://www.tmax.co.kr/proobject/property"
    xmlns:ns9="http://www.tmax.co.kr/proobject/siteConfig"
    resourcePath="com/tmax/flowengine/adapter/dto"
    dtoName="AdapterInfo"
    dtoPath="com/tmax/flowengine/adapter/dto"
    logicalName="AdapterInfoMsgJson"
    physicalName="AdapterInfoMsgJson"
    messageType="JSON"
    trimFlag="RTRIM"
    resourceType="MESSAGE"
>
    <ns4:messageField fieldType="long"      logicalName="id"            physicalName="id"           includeMessagePath="" includeMessageName="" length="16" array="" comments="" metaId="" referencedtoName="UnDeployInnerInfo" align="NONE" fill="" decimal="-1" point="true" sign="false" bitmapNo="" delimiter="" handler="" encodeOption="CHAR" attributeTag="" referenceFieldId="" fieldControlTag="" trimFlag="DEFAULT" dateFormat=""/>
    <ns4:messageField fieldType="String"    logicalName="name"          physicalName="name"         includeMessagePath="" includeMessageName="" length="16" array="" comments="" metaId="" referencedtoName="UnDeployInnerInfo" align="NONE" fill="" decimal="-1" point="true" sign="false" bitmapNo="" delimiter="" handler="" encodeOption="CHAR" attributeTag="" referenceFieldId="" fieldControlTag="" trimFlag="DEFAULT" dateFormat=""/>
    <ns4:messageField fieldType="String"    logicalName="type"          physicalName="type"         includeMessagePath="" includeMessageName="" length="16" array="" comments="" metaId="" referencedtoName="UnDeployInnerInfo" align="NONE" fill="" decimal="-1" point="true" sign="false" bitmapNo="" delimiter="" handler="" encodeOption="CHAR" attributeTag="" referenceFieldId="" fieldControlTag="" trimFlag="DEFAULT" dateFormat=""/>
</ns4:message>
