-- @HyperData Web Server 1.0 @Meta DB @Create Meta

-- PROJECT Table Create SQL
CREATE TABLE HYPERDATA_WEB_SERVER.PROJECT
(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    LAST_EDITED TIMESTAMP NOT NULL,
    CONTENTS VARCHAR(4000) NOT NULL,
    DESCRIPTION VARCHAR(4000) NULL,
    CONSTRAINT PROJECT_PK PRIMARY KEY (ID)
)
/

-- PROJECT_ID_SEQ Sequence Create SQL
CREATE SEQUENCE HYPERDATA_WEB_SERVER.PROJECT_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/

-- MODEL Table Create SQL
CREATE TABLE HYPERDATA_WEB_SERVER.MODEL
(
    ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    AUTHOR VARCHAR(255) NOT NULL,
    STATUS VARCHAR(255) NULL,
    LAST_EDITED TIMESTAMP NOT NULL,
    PROJECT_ID VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(4000) NULL,
    FLOW_ID VARCHAR(4000) NULL,
    CONSTRAINT MODEL_PK PRIMARY KEY (ID)
)
/

ALTER TABLE HYPERDATA_WEB_SERVER.MODEL 
ADD CONSTRAINT FK_PROJECT_ID FOREIGN KEY (PROJECT_ID)
REFERENCES HYPERDATA_WEB_SERVER.PROJECT (ID) ON DELETE CASCADE;
/

-- MODEL_ID_SEQ Sequence Create SQL
CREATE SEQUENCE HYPERDATA_WEB_SERVER.MODEL_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/


-----OLAP META TABLE SQL-----
-- OLAP_PROJECT_INFO_ID_SEQ Sequence Create SQL
CREATE SEQUENCE OLAP_PROJECT_INFO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/

-- OLAP_PROJECT_INFO TABLE CREATE SQL
CREATE TABLE OLAP_PROJECT_INFO
(
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  LAST_EDITED TIMESTAMP NOT NULL,
  CONTENTS VARCHAR(4000),
  DESCRIPTION VARCHAR(4000),
  CONSTRAINT OLAP_PROJECT_PK PRIMARY KEY(ID)
)
/

CREATE UNIQUE INDEX XPKOLAP_PROEJCT_INFO ON OLAP_PROJECT_INFO
(
    NAME                        ASC
)
/

-- OLAP_MODEL_INFO_ID_SEQ Sequence Create SQL
CREATE SEQUENCE OLAP_MODEL_INFO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/

-- OLAP_MODEL_INFO TABLE CREATE SQL
CREATE TABLE OLAP_MODEL_INFO
(
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  LAST_EDITED TIMESTAMP NOT NULL,
  PROJECT_ID NUMBER(10) NOT NULL,
  CONTENTS VARCHAR(4000),
  DESCRIPTION VARCHAR(4000),
  CONSTRAINT OLAP_MODEL_PK PRIMARY KEY(ID)
)
/

CREATE UNIQUE INDEX XPKOLAP_MODEL_INFO ON OLAP_MODEL_INFO
(
    NAME                        ASC
)
/


ALTER TABLE OLAP_MODEL_INFO
ADD CONSTRAINT FK_OLAP_MODEL_INFO FOREIGN KEY (PROJECT_ID)
REFERENCES OLAP_PROJECT_INFO (ID) ON DELETE CASCADE
/

-- OLAP_MODEL_PARAM Table Create SQL
CREATE TABLE OLAP_MODEL_PARAM
(
  MODEL_ID NUMBER(10) NOT NULL,
  REF_FACT_TABLE_ID NUMBER (10) NOT NULL,
  REF_FACT_TABLE_NAME VARCHAR(255) NOT NULL,
  REF_FACT_TABLE_COL_NAME VARCHAR(255) NOT NULL,
  REF_FACT_TABLE_COL_TYPE VARCHAR(255) NOT NULL,
  REF_DIM_TABLE_ID NUMBER (10) NOT NULL,
  REF_DIM_TABLE_NAME VARCHAR(255) NOT NULL,
  REF_DIM_TABLE_COL_NAME VARCHAR(255) NOT NULL,
  REF_DIM_TABLE_COL_TYPE VARCHAR(255) NOT NULL,
  CONSTRAINT OLAP_MODEL_PARAM_PK PRIMARY KEY(MODEL_ID)
)
/

ALTER TABLE OLAP_MODEL_PARAM
ADD CONSTRAINT FK_OLAP_MODEL_PARAM FOREIGN KEY(MODEL_ID)
REFERENCES OLAP_MODEL_INFO (ID) ON DELETE CASCADE
/

-- OLAP_CUBE_INFO_ID_SEQ Sequence Create SQL
CREATE SEQUENCE OLAP_CUBE_INFO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/

-- OLAP_CUBE_INFO Table Create SQL
CREATE TABLE OLAP_CUBE_INFO
(
  ID NUMBER(10) NOT NULL,
  NAME VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  LAST_EDITED TIMESTAMP NOT NULL,
  MODEL_ID NUMBER(10) NOT NULL,
  CONTENTS VARCHAR(4000),
  DESCRIPTION VARCHAR(4000),
  CONSTRAINT OLAP_CUBE_PK PRIMARY KEY (ID)
)
/

CREATE UNIQUE INDEX XPKOLAP_CUBE_INFO ON OLAP_CUBE_INFO
(
    NAME                        ASC
)
/

ALTER TABLE OLAP_CUBE_INFO
ADD CONSTRAINT FK_OLAP_CUBE_INFO FOREIGN KEY (MODEL_ID)
REFERENCES OLAP_MODEL_INFO(ID) ON DELETE CASCADE
/

-- OLAP_CUBE_PARAM Table Create SQL
-- SEL VALUES IS CHECKED FROM MODEL PARAM
CREATE TABLE OLAP_CUBE_FACT_PARAM
(
  CUBE_ID NUMBER(10) NOT NULL,
  SEL_FACT_TABLE_ID NUMBER (10) NOT NULL,
  SEL_FACT_TABLE_NAME VARCHAR(255) NOT NULL,
  SEL_FACT_TABLE_COL_NAME VARCHAR(255) NOT NULL,
  SEL_FACT_TABLE_COL_TYPE VARCHAR(255) NOT NULL,
  CONSTRAINT OLAP_CUBE_FACT_PARAM_PK PRIMARY KEY(CUBE_ID)
)
/

ALTER TABLE OLAP_CUBE_FACT_PARAM
ADD CONSTRAINT FK_OLAP_CUBE_FACT_PARAM FOREIGN KEY(CUBE_ID)
REFERENCES OLAP_CUBE_INFO(ID) ON DELETE CASCADE
/


CREATE TABLE OLAP_CUBE_MEASURE_PARAM
(
  CUBE_ID NUMBER(10) NOT NULL,
  SEL_FACT_TABLE_ID NUMBER (10) NOT NULL,
  SEL_MEASURE_COL_NAME VARCHAR(255) NOT NULL,
  SEL_MEASURE_COL_VALUE VARCHAR(255) NOT NULL,
  SEL_MEASURE_COL_TYPE VARCHAR(255) NOT NULL,
  SEL_MEASURE_COL_EXPRESION VARCHAR(100) NOT NULL,
  CONSTRAINT OLAP_CUBE_MEASURE_PARAM_PK PRIMARY KEY(CUBE_ID)
)
/

CREATE UNIQUE INDEX XPKOLAP_CUBE_MEASURE_PARAM_COL ON OLAP_CUBE_MEASURE_PARAM
(
    SEL_MEASURE_COL_NAME                        ASC
)
/

ALTER TABLE OLAP_CUBE_MEASURE_PARAM
ADD CONSTRAINT FK_OLAP_CUBE_MEASURE_PARAM FOREIGN KEY(CUBE_ID)
REFERENCES OLAP_CUBE_INFO(ID) ON DELETE CASCADE
/


CREATE TABLE OLAP_CUBE_DIM_PARAM
(
  CUBE_ID NUMBER(10) NOT NULL,
  SEL_DIM_TABLE_ID NUMBER (10) NOT NULL,
  SEL_DIM_TABLE_NAME VARCHAR(255) NOT NULL,
  SEL_DIM_TABLE_COL_NAME VARCHAR(255) NOT NULL,
  SEL_DIM_TABLE_COL_TYPE VARCHAR(255) NOT NULL,
  CONSTRAINT OLAP_CUBE_DIM_PARMA_PK PRIMARY KEY(CUBE_ID)
)
/

ALTER TABLE OLAP_CUBE_DIM_PARAM
ADD CONSTRAINT FK_OLAP_CUBE_DIM_PARAM FOREIGN KEY(CUBE_ID)
REFERENCES OLAP_CUBE_INFO (ID) ON DELETE CASCADE
/

-- FACT_TABLE_INFO_ID_SEQ Sequence Create SQL
CREATE SEQUENCE FACT_TABLE_INFO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/
-- FACT TABLE INFO TABLE CREATE SQL
CREATE TABLE FACT_TABLE_INFO
(
  FACT_TABLE_ID NUMBER(10) NOT NULL,
  FACT_TABLE_NAME VARCHAR(255) NOT NULL,
  FACT_TABLE_COL_NAME VARCHAR(255) NOT NULL,
  FACT_TABLE_COL_TYPE VARCHAR(255) NOT NULL,
  CONSTRAINT FACT_TABLE_INFO_PK PRIMARY KEY(FACT_TABLE_ID, FACT_TABLE_NAME)
)
/

-- DIM_TABLE_INFO_ID_SEQ Sequence Create SQL
CREATE SEQUENCE DIM_TABLE_INFO_ID_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
/
-- DIM TABLE INFO TABLE CREATE SQL
CREATE TABLE DIM_TABLE_INFO
(
  DIM_TABLE_ID NUMBER(10) NOT NULL,
  DIM_TABLE_NAME VARCHAR(255) NOT NULL,
  DIM_TABLE_COL_NAME VARCHAR(255) NOT NULL,
  DIM_TABLE_COL_TYPE VARCHAR(255) NOT NULL,
  CONSTRAINT DIM_TABLE_INFO_PK PRIMARY KEY(DIM_TABLE_ID, DIM_TABLE_NAME)
)
/

